### ISSUE TITLE
Attaching Android provider to iOS server

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf_ios_support#69]
I run iOS server with my own HTTPS certificate.
I also attached Android provider to the iOS server, and Android devices listed to iOS server successfully.

However, I cannot control device via Control page of iOS server.
Here are chrome network packets:
```
Request URL: https://stf-ios.mydomain.com/api/v1/user/devices (OK)
Request URL: https://stf-ios.mydomain.com/static/app/devices/icon/x24/E30HT.jpg (OK)
Request URL: https://stf-ios.mydomain.com/[object%20Module] (404 Not Found)
```

Questions:
1. Is there something wrong with `[object%20Module]`?.
2. Attaching Android provider to iOS server is possible?
3. Attaching iOS provider to Android server is possible?
4. Should I implement same certificate to Android provider when it is trying to connect to iOS server?. I guess it is not true though.

**iOS server**
server/nginx/nginx.conf:
```
    location ~ "^/d/KOREA_BS_2/([^/]+)/(?<port>[0-9]{3,5})/$" {
      proxy_pass http://{ANDROID_PROVIDER_IP}:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
```
config.json:
```
{
  "xcode_dev_team_id": "xxxxxxxxxx",
  "stf": {
    "ip": "stf-ios.mydomain.com",
    "hostname": "stf-ios.mydomain.com"
  },
  "video": {
    "enabled": true,
    "use_vnc": true,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 10
  },
  "install": {
    "root_path": "./",
    "config_path": "./config.json"
  },
  "network": {
    "interface": "en0"
  }
}
```

**Android provider**
docker-compose.yml:
```
version: '3'
  
volumes:
  storage-temp:

services:
  adb:
    image: ${ADB_IMAGE}
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  provider:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: stf provider --name KOREA_BS_2 --connect-sub tcp://${MASTER_IP}:7250 --connect-push tcp://${MASTER_IP}:7270 --storage-url http://${MASTER_IP}/ --public-ip ${SLAVE_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${MASTER_IP}/d/KOREA_BS_2/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
```
